changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

logFilters:
  - code: YN0005
    level: discard

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery-workspace.cjs
    spec: '@yarnpkg/plugin-snuggery-workspace'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
