on:
  push:
    branches:
      - main
  pull_request:

name: 'Validation'
jobs:
  code-style:
    name: 'Code Style'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        shell: bash
        env:
          YARN_ENABLE_NETWORK: 0
        run: |
          yarn install --immutable --immutable-cache

      - name: 'Check for formatting errors (fix w/ "yarn prettier --write path/to/file")'
        run: |
          yarn prettier --check .
        shell: bash

      - name: 'Check for linting errors (fix w/ "yarn lint -c fix")'
        run: |
          yarn sn lint
        shell: bash

  build-unit:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        shell: bash
        env:
          YARN_ENABLE_NETWORK: 0
        run: |
          yarn install --immutable --immutable-cache

      - name: Build
        shell: bash
        run: |
          yarn sn build

  integration:
    name: 'Run ${{matrix.cli}} ${{matrix.runner}} on node.js ${{matrix.node}} on ${{matrix.os}}'
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 12.x
          - 14.x
          - 16.x
        runner:
          - test
          - jest
        cli:
          - sn
        include:
          # Verify that everything works if using the @angular/cli
          - os: ubuntu-latest
            node: 16.x
            runner: test
            cli: ng
          # Test future node version(s)
          - os: ubuntu-latest
            node: 17.x
            runner: test
            cli: sn

    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js ${{matrix.node}}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}

      - name: Install
        shell: bash
        env:
          YARN_ENABLE_NETWORK: 0
        run: |
          yarn install --immutable --immutable-cache

      - name: 'Run tests'
        shell: bash
        run: |
          yarn ${{matrix.cli}} ${{matrix.runner}} integration
